# Generated by Django 3.1 on 2020-08-12 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prod_image',
            field=models.ImageField(default='default.jpg', upload_to='product_images'),
        ),
    ]
